### ISSUE TITLE
Number of Groups Returned

### ISSUE THREAD

**Issue by gmccauley** [matbe/MEMDocumentAndExporter#3]
Looks like the script is returning a maximum of 100 groups.  We currently have 302 groups in our AzureAD instance and only 100 are being returned.

**Comment by matbe** [comment]
100 is the default limit for returned object when using graph. I will update the script so you can define how many results should be returned.

**Comment by matbe** [comment]
Updated the code now so download and try again.

**Comment by gmccauley** [comment]
Confirmed that this is resolved.  Thanks Mucho!

**Comment by matbe** [comment]
Pefect, thanks for the feedback!
