### ISSUE TITLE
$ProcessvppTokens using Invoke-GraphClassExpand

### ISSUE THREAD

**Issue by portaldotjay** [matbe/MEMDocumentAndExporter#5]
vppTokens don't have assignments. Editing line 894 to use Invoke-GraphClass sorts out the errors generated by it.

**Comment by matbe** [comment]
Thanks for reporting, have you verified that the export and documentation look good as well after this? I dont have any vpp tokens so cant verify myself.

**Comment by portaldotjay** [comment]
All were added to the doc and JSONs were exported, but there was no heading for the individual VPP tokens in the doc so they show up blank in ToC. 
![image](https://user-images.githubusercontent.com/25699763/75056301-9b3ee880-548b-11ea-9d7f-7f825c5d8633.png)

**Comment by matbe** [comment]
Ok I’m working blind here since I dont have any vpptokens myself so could you please explain what the expected result should be? Is the json empty as well? Thank you for taking your time to help.

**Comment by portaldotjay** [comment]
No problem. This is a great tool that's going to save me and others a ton of time. Happy to help. I would expect to see displayName there. The JSON exports are full and seem to be complete. 
![image](https://user-images.githubusercontent.com/25699763/75065771-55d7e680-549e-11ea-9028-0086c0eeabef.png)

**Comment by matbe** [comment]
So it is the value in the “displayname” attribute that should be the title for each section? Is that correct? If possible could you send me the json? DM me on twitter and I’ll send my email. You can remove any identifiable values, I’m mostly interested in the layout.

**Comment by matbe** [comment]
Was this fixed and can be closed or can I do anything more to improve it?

**Comment by portaldotjay** [comment]
Yeah! I haven't ran it since our twitter chats but our discussion seems like it was cleared up.
