### ISSUE TITLE
AzureADPreview needed in the Requires section

### ISSUE THREAD

**Issue by mdcaddic** [matbe/MEMDocumentAndExporter#6]
With AzureADPreview installed (but not AzureAD) I needed to change line 36 to 
#Requires -Modules AzureADPreview,PSWriteWord

**Comment by matbe** [comment]
Fixed in commit e21b6f6dc7644315dc7775083b266fb2cefea781 , the azuremodule requirement is already checked in the "Get-AuthToken" function so removed it from the #requires statement. 

Thank you for reporting!
