### ISSUE TITLE
found a huge amount of mobile apps which i can't find in neither in endpointmanager nor in the MSFB

### ISSUE THREAD

**Issue by nitram-rem** [matbe/MEMDocumentAndExporter#7]
IN endpoint i have a couple of apps configured. I can find them all in the export but i can also find a bigger amount of apps which i haven't configured or ever used at all. Stuff like Blue jeans video or whatever it is called. I have no idea where this apps come from. Everything else is completely correct and is correct documented

**Comment by matbe** [comment]
These apps are the ones you see if you choose _Intune/Apps/"+Add"_ Then choose the type "Built in Apps" and "select apps".
I think i have found the attribute that determines if they are just available or actually added to your tenant.
Will do some more testing and push an updated version soon.

**Comment by matbe** [comment]
Fixed in c53e38b 
Let me know if it works better now.
You will need to update the XML as well since I added a new option called SfBApps, this switch allows you to choose if you want to document Store for Business apps or not.

**Comment by nitram-rem** [comment]
Thanks for the update and information. Will give it a try tommorow and keep 
you informed.

Viele Grüße / kind regards

Martin Böhmer

Gesendet vom Handy.


Mit freundlichen Grüßen / kind regards

Martin Böhmer
Am 14. Januar 2021 16:30:53 schrieb Matt Benninge <notifications@github.com>:
